Algoritmo "Concatenação"
// Descrição   : Concatenacao
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/10/2022
Var
// Seção de Declarações das variáveis 
   nome: caractere
   numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o nome:")
   leia(nome)
   escreval("Digite o numero:")
   leia(numero)
   
   escreval(nome, " : ", numero, 15)

Fimalgoritmo