Algoritmo "Operadores Relacionais"
// Descrição   : Operadores Relacionais
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/10/2022
Var
// Seção de Declarações das variáveis 
   nota01, nota02: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota01:= 10
   nota02:= 15
   
   se (nota01 = nota02) então
      escreval ("Nota01 é diferente")
   senao
      escreval("Nota01 é igual")
   fimse

Fimalgoritmo